# -*- coding: utf-8 -*-
"""Sea Level Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZS4HugDDlj4BXOem86MPRjn5VtcIJIz
"""

import pandas as pd

# Create the dataset
data = {
    "Year": [1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890],
    "CSIRO Adjusted Sea Level": [0.0, 0.03, 0.06, 0.08, 0.1, 0.12, 0.14, 0.17, 0.19, 0.21, 0.23],
    "Lower Error": [-0.1]*11,
    "Upper Error": [0.1]*11
}

df = pd.DataFrame(data)

# Save as CSV
df.to_csv("epa-sea-level.csv", index=False)

print("CSV file created successfully!")

from google.colab import files
files.download("epa-sea-level.csv")

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress

# Load data
df = pd.read_csv("epa-sea-level.csv")

# Create scatter plot
plt.figure(figsize=(10,6))
plt.scatter(df['Year'], df['CSIRO Adjusted Sea Level'], color='blue', label='Data Points')

# Line of best fit (all data)
slope_all, intercept_all, *_ = linregress(df['Year'], df['CSIRO Adjusted Sea Level'])
years_all = pd.Series(range(df['Year'].min(), 2051))
plt.plot(years_all, intercept_all + slope_all*years_all, color='red', label='Best Fit: All Data')

# Line of best fit (2000 onward)
df_recent = df[df['Year'] >= 2000]
slope_recent, intercept_recent, *_ = linregress(df_recent['Year'], df_recent['CSIRO Adjusted Sea Level'])
years_recent = pd.Series(range(2000, 2051))
plt.plot(years_recent, intercept_recent + slope_recent*years_recent, color='green', label='Best Fit: 2000+')

# Labels and title
plt.xlabel("Year")
plt.ylabel("Sea Level (inches)")
plt.title("Rise in Sea Level")
plt.legend()
plt.show()